# config/packages/scheb_two_factor.yaml
scheb_two_factor:
    security_tokens:
        - scheb_two_factor.security.token_provider
    totp:
        enabled: true
        # You can configure additional options here if needed
