controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Login route
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

# Homepage route
app_homepage:
    path: /
    controller: App\Controller\HomepageController::index
app_rooms:
    path: /rooms
    controller: App\Controller\RoomController::index

app_room_add:
    path: /rooms/add
    controller: App\Controller\RoomController::add
room_edit:
    path: /room/{name}/edit
    controller: App\Controller\RoomController::edit

room_delete:
    path: /room/{name}/delete
    controller: App\Controller\RoomController::delete
    methods: POST