# Attribute-based routing for controllers
controllers:
    resource: '../src/Controller/'
    type: attribute

# Login route
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

# Homepage route
app_homepage:
    path: /
    controller: App\Controller\HomepageController::index

# Rooms routes
app_rooms:
    path: /rooms
    controller: App\Controller\RoomController::index

app_room_add:
    path: /rooms/add
    controller: App\Controller\RoomController::add

room_edit:
    path: /room/{name}/edit
    controller: App\Controller\RoomController::edit

room_delete:
    path: /room/{name}/delete
    controller: App\Controller\RoomController::delete
    methods: POST

# Schedule routes
schedule_index:
    path: /schedule
    controller: App\Controller\ScheduleController::index

schedule_new:
    path: /schedule/new
    controller: App\Controller\ScheduleController::new

schedule_edit:
    path: /schedule/{id}/edit
    controller: App\Controller\ScheduleController::edit

schedule_delete:
    path: /schedule/{id}/delete
    controller: App\Controller\ScheduleController::delete
    methods: POST
    
reservation_new:
    path: /reservation/new/{scheduleId}
    controller: App\Controller\ReservationController::new
    methods: ['GET', 'POST']
reservation_index:
    path: /reservations
    controller: App\Controller\ReservationController::index
    methods: GET
reservation_edit:
    path: /reservation/{id}/edit
    controller: App\Controller\ReservationController::edit
    methods: ['GET', 'POST']

reservation_delete:
    path: /reservation/{id}/delete
    controller: App\Controller\ReservationController::delete
    methods: POST

