# Attribute-based routing for controllers
controllers:
    resource: '../src/Controller/'
    type: attribute

# Login route
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

# Homepage route
app_homepage:
    path: /
    controller: App\Controller\HomepageController::index

# Rooms routes
app_rooms:
    path: /rooms
    controller: App\Controller\RoomController::index

app_room_add:
    path: /rooms/add
    controller: App\Controller\RoomController::add

room_edit:
    path: /room/{name}/edit
    controller: App\Controller\RoomController::edit

room_delete:
    path: /room/{name}/delete
    controller: App\Controller\RoomController::delete
    methods: POST

# Schedule routes
schedule_index:
    path: /schedule
    controller: App\Controller\ScheduleController::index

schedule_new:
    path: /schedule/new
    controller: App\Controller\ScheduleController::new

schedule_edit:
    path: /schedule/{id}/edit
    controller: App\Controller\ScheduleController::edit

schedule_delete:
    path: /schedule/{id}/delete
    controller: App\Controller\ScheduleController::delete
    methods: POST
    
reservation_search:
    path: /reservation/search
    controller: App\Controller\ReservationController::search
    methods: [GET, POST]

reservation_new:
    path: /reservation/new/{scheduleId}
    controller: App\Controller\ReservationController::new
    methods: [GET, POST]

reservation_index:
    path: /reservation/
    controller: App\Controller\ReservationController::index
    methods: [GET]

reservation_edit:
    path: /reservation/{id}/edit
    controller: App\Controller\ReservationController::edit
    methods: [GET, POST]
    requirements:
        id: \d+

reservation_delete:
    path: /reservation/{id}/delete
    controller: App\Controller\ReservationController::delete
    methods: [POST]
    requirements:
        id: \d+
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register
room_statistics:
    path: /room/{id}/statistics
    controller: App\Controller\RoomController::showStatistics
    methods: [GET]
reservation_success:
    path: /reservation/success
    controller: App\Controller\ReservationController::success
    methods: GET
2fa_login:
    path: /2fa
    controller: App\Controller\SecurityController::twoFactor
2fa_login_check:
    path: /2fa_check
two_factor_setup:
    path: /2fa/setup
    controller: App\Controller\TwoFactorController::setup
admin_users:
    path: /admin/users
    controller: App\Controller\AdminController::listUsers
    methods: [GET]
room_availability:
    path: /room/availability
    controller: App\Controller\RoomController::availability