# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\TwoFactorController:
        arguments:
            $qrCodeBuilder: '@Endroid\QrCode\Builder\BuilderInterface'

    # QR Code builder service definition
    Endroid\QrCode\Builder\BuilderInterface:
        factory: ['Endroid\QrCode\Builder\Builder', 'create']

    # 2FA Authentication Handlers
    App\Security\AuthenticationSuccessHandler:
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    App\Security\TwoFactorAuthenticationRequiredHandler:
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    App\Security\TwoFactorAuthenticationSuccessHandler:
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    App\Security\TwoFactorAuthenticationFailureHandler:
        tags:
            - { name: 'monolog.logger', channel: 'security' }
