# config/services.yaml

services:
    _defaults:
        autowire: true        # Automatically inject dependencies
        autoconfigure: true   # Automatically register services as events or command handlers

    # Register all services in the 'src/' directory, excluding certain paths
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # QR Code builder service definition
    Endroid\QrCode\Builder\BuilderInterface:
        factory: ['Endroid\QrCode\Builder\Builder', 'create']

    # 2FA Authentication Handlers
    App\Security\AuthenticationSuccessHandler:
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    App\Security\TwoFactorAuthenticationRequiredHandler:
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    App\Security\TwoFactorAuthenticationSuccessHandler:
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    App\Security\TwoFactorAuthenticationFailureHandler:
        tags:
            - { name: 'monolog.logger', channel: 'security' }

    # Explicitly register repositories if autowiring does not work
    App\Repository\ReservationRepository:
        arguments:
            $registry: '@doctrine'

    App\Repository\RoomRepository:
        arguments:
            $registry: '@doctrine'
